# Generated by Django 6.0 on 2026-05-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('blusa', 'Blusa'), ('calca', 'Calca'), ('shorts', 'Shorts'), ('bermuda', 'Bermuda'), ('saia', 'Saia'), ('meia', 'Meia'), ('legging', 'Legging'), ('vestido', 'Vestido'), ('camisa', 'Camisa'), ('camiseta', 'Camiseta'), ('conjunto_feminino', 'Conjunto_Feminino'), ('conjunto_masculino', 'Conjunto_Masculino'), ('jaqueta', 'Jaqueta'), ('moletom', 'Moletom'), ('body', 'Body'), ('colete', 'Colete'), ('calca_jeans', 'Calca_Jeans'), ('calcado', 'Calçado'), ('acessorio', 'Acessório')], max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('colecao', models.CharField(max_length=50)),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('RN', 'RN'), ('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XGG', 'XGG'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('06', '06'), ('08', '08'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='produto.produto')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
                'ordering': ['tamanho'],
            },
        ),
    ]
