# Generated by Django 6.0 on 2026-05-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('blusa', 'Blusa'), ('calça', 'Calça'), ('shorts', 'Shorts'), ('bermuda', 'Bermuda'), ('saia', 'Saia'), ('meia', 'Meia'), ('legging', 'Legging'), ('vestido', 'Vestido'), ('camisa', 'Camisa'), ('camiseta', 'Camiseta'), ('conjunto_feminino', 'Conjunto Feminino'), ('conjunto_masculino', 'Conjunto Masculino'), ('jaqueta', 'Jaqueta'), ('moletom', 'Moletom'), ('body', 'Body'), ('colete', 'Colete'), ('calca_jeans', 'Calça Jeans'), ('calcado', 'Calçado'), ('acessorio', 'Acessório')], max_length=50),
        ),
        migrations.AlterField(
            model_name='produtovariacao',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
